// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResetService.Infrastructure.Persistence;

#nullable disable

namespace ResetService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResetServiceDbContext))]
    [Migration("20260814133256_InitialPersistenceBaseline")]
    partial class InitialPersistenceBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");
#pragma warning restore 612, 618
        }
    }
}
